name: Deploy to Azure Blob

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Upload to Azure
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az storage blob upload-batch \
          --destination '$web' \
          --source . \
          --connection-string "${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}"
